version: '3.8'
services:
  tongue:
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    build: .
    ports:
      - "8000:8000"
    environment:
      - COQUI_TOS_AGREED=1
    volumes:
      - ./app:/app/app
      - model_cache:/app/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  model_cache: